#!/usr/bin/env python3
"""Generate the reference documentation from the code.

Three documents come out of here, and all three are derived rather than
written, so they cannot drift from the implementation:

    docs/REFERENCE.md  the DOCSIS tables -- message types, IUCs, every TLV
                       namespace, timers -- read straight out of consts.py,
                       plus the channel and timing arithmetic evaluated for
                       the default lab
    docs/CLI.md        every `docsis` subcommand (from the argparse tree) and
                       every CMTS shell command (from the Cli command table)
    docs/API.md        a module map built from the package's own docstrings

`tests/test_docs.py` regenerates them into a temporary directory and fails if
anything differs, so a change to the code that should have changed the docs
does not slip through.

    ./docsis docs            # regenerate in place
    ./docsis docs --check    # fail if they are stale
"""

from __future__ import annotations

import argparse
import ast
import datetime
import inspect
import io
import os
import pathlib
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

from docsislab.docsis import consts as C
from docsislab.docsis.cfgfile import CMTS_MIC_ORDER
from docsislab.phy.channel import (ANNEX_B_TS_BPS, DOCSIS_1X_MAX_KSYM,
                                   SYMBOL_RATES, DownstreamChannel,
                                   UpstreamChannel)
from docsislab.phy.plant import (LOSS_DB_PER_KM, MAX_RESIDUAL_LOSS_DB,
                                 VELOCITY_FACTOR, delay_for_km)
from docsislab.util import clock as K

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

GENERATED = ("<!-- Generated by tools/gen_docs.py -- do not edit by hand. "
             "Run `./docsis docs` to regenerate. -->")


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------

def cell(value) -> str:
    """A table cell.  A literal pipe would end the column, so escape it --
    which matters here because CLI argument syntax is full of them."""
    return str(value).replace("|", "\\|").replace("\n", " ")


def table(out: io.StringIO, headers: list[str], rows: list[list[str]]) -> None:
    out.write("| " + " | ".join(cell(h) for h in headers) + " |\n")
    out.write("| " + " | ".join("---" for _ in headers) + " |\n")
    for row in rows:
        out.write("| " + " | ".join(cell(c) for c in row) + " |\n")
    out.write("\n")


def enum_rows(enum, notes: dict[int, str] | None = None) -> list[list[str]]:
    notes = notes or {}
    seen: dict[int, str] = {}
    for member in enum:
        seen.setdefault(int(member), member.name)
    return [[str(value), f"`{name}`", notes.get(value, "")]
            for value, name in sorted(seen.items())]


def enum_doc(enum) -> str:
    """The enum's own one-line description, if it has one."""
    doc = inspect.getdoc(enum) or ""
    first = doc.split("\n\n")[0].replace("\n", " ").strip()
    # IntEnum supplies a generic docstring when the class has none.
    return "" if first.startswith("An enumeration") or "int" == first else first


def enum_table(out: io.StringIO, enum, notes: dict[int, str] | None = None,
                value_header: str = "Value") -> None:
    """Heading-free enum section: its docstring, then its members."""
    doc = enum_doc(enum)
    if doc:
        out.write(doc + "\n\n")
    table(out, [value_header, "Name", "Notes"], enum_rows(enum, notes))


# --------------------------------------------------------------------------
# REFERENCE.md
# --------------------------------------------------------------------------

MGMT_NOTES = {
    1: "carried in a Timing header, not a MAC management header",
    2: "DOCSIS 1.x view of an upstream channel",
    3: "must be version 1; DOCSIS 3.1 reused version 5",
    4: "SID 0 for initial ranging",
    29: "DOCSIS 2.0 view: adds the advanced-PHY IUCs and S-CDMA parameters",
    30: "not used here; A-TDMA ranging uses RNG-REQ",
    33: "DOCSIS 3.0",
    35: "DOCSIS 3.0",
}

IUC_NOTES = {
    1: "contention region for bandwidth requests",
    3: "broadcast; sized for a burst plus the plant round trip, so the whole "
       "region is one transmit opportunity",
    4: "unicast; fast while ranging, slow once online",
    7: "terminates the last grant in a MAP",
    9: "DOCSIS 2.0 only",
    10: "DOCSIS 2.0 only",
    11: "DOCSIS 2.0 only",
}

CAP_NOTES = {
    2: "how the CMTS learns it is talking to a 2.0 modem",
    9: "802.1P/802.1Q filtering",
    21: "bitmask; bit 5 (5120 ksym/s) exists only on a 2.0 transmitter",
}

CFG_NOTES = {
    3: "0 registers the modem but forwards nothing (`online(d)`)",
    5: "added by the modem in REG-REQ; never in the config file",
    6: "unkeyed MD5 over the settings -- detects corruption only",
    7: "MD5 over an ordered subset plus the shared secret",
    29: "0 skips BPI+ entirely",
    255: "no length byte",
}

TIMERS = [
    ("lost sync", C.LOST_SYNC_TIMEOUT, "a SYNC message"),
    ("T1", C.T1_UCD_WAIT, "a usable UCD"),
    ("T2", C.T2_INITIAL_MAINT_WAIT, "a broadcast Initial Maintenance opportunity"),
    ("T3", C.T3_RNG_RSP_WAIT, "a RNG-RSP"),
    ("T4", C.T4_STATION_MAINT_WAIT, "a unicast Station Maintenance opportunity"),
    ("T5", C.T5_UCC_RSP_WAIT, "a UCC-RSP"),
    ("T6", C.T6_REG_RSP_WAIT, "a REG-RSP"),
    ("T7", C.T7_DSX_RSP_WAIT, "a DSA/DSC response"),
    ("T8", C.T8_DSX_ACK_WAIT, "a DSA/DSC acknowledgement"),
]


def reference() -> str:
    out = io.StringIO()
    w = out.write
    w("# DOCSIS 2.0 reference\n\n")
    w(GENERATED + "\n\n")
    w("Every table below is read out of the code, so it says what this\n"
      "implementation actually does rather than what it was meant to do.\n"
      "Section numbers refer to CM-SP-RFIv2.0.\n\n")

    # -- timebase -------------------------------------------------------
    w("## Timebase\n\n")
    table(out, ["Quantity", "Value", "Notes"], [
        ["master clock", f"{K.MASTER_CLOCK_HZ / 1e6:.2f} MHz",
         f"32-bit counter, wraps every {K.TIMESTAMP_WRAP_S:.2f} s"],
        ["timebase tick", f"{K.TICK_S * 1e6:.2f} µs",
         f"{K.COUNTS_PER_TICK} master clock counts"],
        ["mini-slot", "M ticks", "M a power of two; the unit MAPs allocate in"],
        ["timing adjust unit", f"{K.TIMING_ADJUST_UNIT_S * 1e9:.5f} ns",
         "1/64 tick = one master clock count; the RNG-RSP resolution"],
    ])

    # -- frame control --------------------------------------------------
    w("## MAC frame control\n\n")
    w("```\n"
      "+----+----------+-----------+----------+-----+---------+\n"
      "| FC | MAC_PARM |  LEN/SID  |   EHDR   | HCS | payload |\n"
      "+----+----------+-----------+----------+-----+---------+\n"
      "  1       1           2       0..240      2\n"
      "\n"
      "FC:  bits 7..6  FC_TYPE\n"
      "     bits 5..1  FC_PARM\n"
      "     bit  0     EHDR_ON\n"
      "```\n\n")
    w("LEN counts the extended header **as well as** the payload (Table 6-3),\n"
      "and a Packet PDU carries the whole Ethernet frame including its FCS.\n\n")
    w("### FC_TYPE\n\n")
    enum_table(out, C.FCType)
    w("### FC_PARM, when FC_TYPE is `MAC_SPECIFIC`\n\n")
    enum_table(out, C.FCParm, {
        0: "carries SYNC",
        2: "a bare 6-byte frame: MAC_PARM is a mini-slot count, LEN/SID a SID",
        0x1C: "several MAC frames in one burst",
    })
    w("### Extended header element types\n\n")
    enum_table(out, C.EHdrType)
    w("### Header Check Sequence\n\n")
    from docsislab.util.crc import HCS_LITTLE_ENDIAN, HCS_VARIANT
    w(f"CRC-16 variant `{HCS_VARIANT}` (poly 0x1021, init 0xFFFF, reflected "
      f"in and out, final complement -- the HDLC FCS-16), transmitted "
      f"{'least' if HCS_LITTLE_ENDIAN else 'most'}-significant byte first. "
      f"See `docs/WIRESHARK.md` for how that was established.\n\n")

    # -- management messages --------------------------------------------
    w("## MAC management messages\n\n")
    w("The `version` byte says which revision of the spec a reader needs. "
      "Types this implementation encodes are marked.\n\n")
    rows = []
    for member in C.MgmtType:
        version = C.MGMT_MSG_VERSION.get(member)
        rows.append([str(int(member)), f"`{member.name}`",
                     str(version) if version else "—",
                     MGMT_NOTES.get(int(member), "")])
    table(out, ["Type", "Name", "Version", "Notes"], rows)
    w(f"Management messages are addressed to "
      f"`{':'.join(f'{b:02x}' for b in C.DOCSIS_MGMT_MULTICAST)}` when "
      f"broadcast to every modem on the downstream.\n\n")

    # -- IUCs -----------------------------------------------------------
    w("## Interval Usage Codes\n\n")
    rows = [[str(v), f"`{n}`", C.IUC_NAMES.get(int(v), ""), IUC_NOTES.get(int(v), "")]
            for v, n in ((int(m), m.name) for m in C.IUC)]
    table(out, ["IUC", "Name", "Usage", "Notes"], rows)

    # -- SIDs -----------------------------------------------------------
    w("## Service Identifiers\n\n")
    table(out, ["Value", "Meaning"], [
        [str(C.SID_INITIAL_RANGING), "a modem that has not been given a SID yet"],
        [f"1..{C.SID_MAX_UNICAST}", "unicast"],
        [f"{C.SID_BROADCAST} (0x3FFF)", "broadcast / null"],
    ])

    # -- UCD ------------------------------------------------------------
    w("## Upstream Channel Descriptor\n\n")
    w("Fixed part: upstream channel ID, configuration change count, mini-slot "
      "size in ticks, downstream channel ID. Then TLVs:\n\n")
    enum_table(out, C.UCDTLV, {
        1: "in units of 160 ksym/s",
        4: "DOCSIS 1.x burst descriptor",
        5: "DOCSIS 2.0 burst descriptor",
    }, value_header="Type")
    w("### Burst descriptor sub-TLVs\n\n")
    w("The IUC is the first byte of the descriptor value; these follow. "
      "Types 12 and above are only legal in a type-5 (DOCSIS 2.0) "
      "descriptor.\n\n")
    enum_table(out, C.BurstTLV, {
        5: "T, correctable bytes per codeword; 0 disables FEC",
        6: "k, information bytes per codeword",
        8: "mini-slots; 0 is unlimited",
        9: "symbols",
        14: "1 = QPSK0, 2 = QPSK1",
    }, value_header="Sub-TLV")
    w("### Modulation\n\n")
    rows = [[str(int(m)), f"`{m.name}`", C.MODULATION_NAMES.get(int(m), ""),
             str(C.BITS_PER_SYMBOL.get(m, ""))] for m in C.Modulation]
    table(out, ["Value", "Name", "Label", "Bits/symbol"], rows)

    # -- MAP ------------------------------------------------------------
    w("## MAP information element\n\n")
    w("```\n"
      " 31                18 17    14 13                 0\n"
      "+--------------------+--------+-------------------+\n"
      "|      SID (14)      | IUC (4)|    offset (14)    |\n"
      "+--------------------+--------+-------------------+\n"
      "```\n\n"
      "A grant runs from its own offset to the offset of the *next* element, "
      "which is why a MAP always ends with a Null IE.\n\n")

    # -- ranging --------------------------------------------------------
    w("## Ranging Response\n\n")
    enum_table(out, C.RngRspTLV, {
        1: "signed 32-bit, in units of 1/64 tick",
        2: "signed 8-bit, 0.25 dB steps",
        3: "signed 16-bit, Hz",
    }, value_header="Type")
    w("### Ranging status\n\n")
    enum_table(out, C.RangingStatus, {
        1: "keep ranging, more adjustment needed",
        2: "give up and re-initialise the MAC",
        3: "ranging complete",
    })

    # -- registration ---------------------------------------------------
    w("## Configuration settings\n\n")
    w("Used in the configuration file and echoed back in REG-REQ.\n\n")
    enum_table(out, C.CfgTLV, CFG_NOTES, value_header="Type")
    w("### Class of Service sub-TLVs (type 4)\n\n")
    enum_table(out, C.ClassOfServiceTLV, value_header="Sub-TLV")
    w("### Modem Capabilities sub-TLVs (type 5)\n\n")
    w("Numbering runs contiguously from 1 with no gap; a gap shifts every "
      "field after it.\n\n")
    enum_table(out, C.CapTLV, CAP_NOTES, value_header="Sub-TLV")
    w("### Upstream symbol rate bitmask (capability 21)\n\n")
    table(out, ["Bit", "Symbol rate", "Notes"], [
        [f"0x{int(m):02x}", m.name.replace("KSPS_", "") + " ksym/s",
         "DOCSIS 2.0 only" if int(m) == 0x20 else ""]
        for m in C.UpstreamSymbolRate])
    w(f"A DOCSIS 2.0 modem advertises `0x{C.SYMBOL_RATES_DOCSIS_20:02X}`; "
      f"a 1.x modem `0x{C.SYMBOL_RATES_DOCSIS_1X:02X}`.\n\n")
    w("### Service Flow sub-TLVs (types 24 and 25)\n\n")
    enum_table(out, C.SFTLV, {
        1: "the config file carries references; the CMTS assigns the real ids",
        2: "assigned by the CMTS",
        3: "upstream only",
    }, value_header="Sub-TLV")
    w("### QoS parameter set\n\n")
    enum_table(out, C.QoSParamSet)
    w("### Scheduling type\n\n")
    enum_table(out, C.SchedulingType)
    w("### DOCSIS version (capability 5.2)\n\n")
    enum_table(out, C.DocsisVersion)
    w("### Registration response codes\n\n")
    enum_table(out, C.RegRspCode)
    w("### Confirmation codes\n\n")
    enum_table(out, C.ConfirmationCode)

    # -- MICs -----------------------------------------------------------
    w("## The two configuration-file MICs\n\n")
    w("The **CM MIC** (TLV 6) is an MD5 over every configuration setting in "
      "file order except the two MIC settings. It detects a corrupted "
      "download and nothing more -- anyone can recompute it.\n\n")
    w("The **CMTS MIC** (TLV 7) is an MD5 over the settings below, *in this "
      "order*, with the shared secret appended. The order is normative: two "
      "implementations that disagree about it fail to authenticate each other "
      "even with the same secret.\n\n")
    table(out, ["#", "Type", "Name"], [
        [str(i + 1), str(int(t)), f"`{C.CfgTLV(int(t)).name}`"]
        for i, t in enumerate(CMTS_MIC_ORDER)])

    # -- timers ---------------------------------------------------------
    w("## Timers\n\n")
    table(out, ["Timer", "Value", "Waiting for"], [
        [name, f"{value * 1000:.0f} ms" if value < 1 else f"{value:g} s", what]
        for name, value, what in TIMERS])
    table(out, ["Limit", "Value", ""], [
        ["SYNC interval (max)", f"{C.SYNC_INTERVAL_MAX * 1000:.0f} ms", ""],
        ["UCD interval (max)", f"{C.UCD_INTERVAL_MAX:g} s", ""],
        ["ranging retries", str(C.RNG_RETRIES),
         "consecutive T3 timeouts before the modem abandons the channel"],
        ["contention ranging retries", str(C.CONTENTION_RANGING_RETRIES), ""],
    ])

    # -- channels -------------------------------------------------------
    w("## Channel arithmetic\n\n")
    w("### Downstream (ITU-T J.83 Annex B)\n\n")
    rows = []
    for mod, ts in sorted(ANNEX_B_TS_BPS.items()):
        ds = DownstreamChannel(modulation=mod)
        rows.append([C.MODULATION_NAMES[mod], f"{ts / 1e6:.5f}",
                     f"{ds.payload_bps / 1e6:.3f}",
                     f"{ds.serialization_s(1518) * 1e6:.1f}"])
    table(out, ["Modulation", "MPEG-TS Mbit/s", "DOCSIS payload Mbit/s",
                "1518-byte frame (µs)"], rows)
    w("The payload rate is the transport-stream rate times 184/188, since "
      "each 188-byte TS packet carries a 4-byte header.\n\n")

    w("### Upstream channel widths\n\n")
    rows = []
    for width, ksym in sorted(SYMBOL_RATES.items()):
        us = UpstreamChannel(width_hz=width)
        rows.append([f"{width / 1e6:.1f}", str(ksym),
                     "yes" if ksym <= DOCSIS_1X_MAX_KSYM else "**no**",
                     f"{us.raw_bps() / 1e6:.2f}"])
    table(out, ["Width (MHz)", "ksym/s", "Describable by a type-2 UCD",
                "64-QAM raw Mbit/s"], rows)
    w(f"DOCSIS 1.x stops at {DOCSIS_1X_MAX_KSYM} ksym/s, so a 6.4 MHz channel "
      f"cannot be expressed in a type-2 UCD at all and is invisible to a 1.x "
      f"modem.\n\n")

    w("### Mini-slot capacity, default lab upstream\n\n")
    us = UpstreamChannel()
    w(f"{us.describe()}\n\n")
    rows = []
    for prof in us.burst_profiles:
        iuc = prof.iuc
        rows.append([str(int(iuc)), C.IUC_NAMES.get(int(iuc), ""),
                     C.MODULATION_NAMES.get(prof.modulation, ""),
                     f"T={prof.fec_t} k={prof.fec_k}",
                     str(us.bytes_per_minislot(iuc)),
                     str(us.minislots_for(64, iuc)),
                     str(us.minislots_for(1518, iuc))])
    table(out, ["IUC", "Usage", "Modulation", "FEC", "Bytes/mini-slot",
                "Mini-slots for 64 B", "for 1518 B"], rows)
    w("A mini-slot is a slice of *time*, so its byte capacity depends entirely "
      "on the burst profile the grant was issued under. The mini-slot counts "
      "include Reed-Solomon parity, preamble and guard time, which is why they "
      "exceed a naive division.\n\n")

    # -- plant ----------------------------------------------------------
    w("## Plant\n\n")
    w(f"Velocity of propagation {VELOCITY_FACTOR}c, coaxial loss "
      f"{LOSS_DB_PER_KM} dB/km bounded at {MAX_RESIDUAL_LOSS_DB:.0f} dB to "
      f"stand in for the amplifier cascade a real plant is built with.\n\n")
    rows = []
    for km in (1, 5, 10, 25, 50, 80, 160):
        d = delay_for_km(km)
        rows.append([str(km), f"{d * 1e6:.2f}", f"{2 * d * 1e6:.2f}",
                     str(round(2 * d / K.TIMING_ADJUST_UNIT_S)),
                     f"{min(km * LOSS_DB_PER_KM, MAX_RESIDUAL_LOSS_DB):.1f}"])
    table(out, ["Distance (km)", "One way (µs)", "Round trip (µs)",
                "Ranging offset (units)", "Residual loss (dB)"], rows)
    w("The ranging offset a modem converges on *is* its distance from the "
      "CMTS, which is the single most useful thing to watch in a run.\n\n")

    # -- states ---------------------------------------------------------
    from docsislab.cm.cm import STATE_MEANING as CM_STATES
    from docsislab.cmts.modemdb import STATE_MEANING as CMTS_STATES
    w("## States\n\n")
    w("### CMTS-side, as reported by `show cable modem`\n\n")
    table(out, ["State", "Meaning"],
          [[f"`{k}`", v] for k, v in CMTS_STATES.items()])
    w("### Modem-side, as reported by `show cm`\n\n")
    table(out, ["State", "Meaning"],
          [[f"`{k.value}`", v] for k, v in CM_STATES.items()])
    return out.getvalue()


# --------------------------------------------------------------------------
# CLI.md
# --------------------------------------------------------------------------

def cli_doc() -> str:
    from docsislab.__main__ import build_parser
    from docsislab.cmts.cli import Cli
    from docsislab.lab.runner import Lab, LabOptions
    from docsislab.lab.topology import Topology

    out = io.StringIO()
    w = out.write
    w("# Command reference\n\n")
    w(GENERATED + "\n\n")
    w("Two command sets: the `docsis` program that runs and inspects a lab, "
      "and the CMTS-style shell you get inside `docsis cli`.\n\n")

    parser = build_parser()
    sub = next(a for a in parser._actions
               if isinstance(a, argparse._SubParsersAction))

    w("## `docsis`\n\n")
    table(out, ["Subcommand", "Purpose"],
          [[f"`{name}`", (p.description or "").strip().split("\n")[0]
            or sub._choices_actions[i].help or ""]
           for i, (name, p) in enumerate(sub.choices.items())])

    for name, sp in sub.choices.items():
        w(f"### `docsis {name}`\n\n")
        helps = {a.dest: a for a in sub._choices_actions}
        summary = helps[name].help if name in helps else ""
        if summary:
            w(f"{summary[0].upper()}{summary[1:]}.\n\n")
        usage = sp.format_usage().replace("usage: ", "").strip()
        w("```\n" + usage + "\n```\n\n")
        rows = []
        for action in sp._actions:
            if action.dest == "help" or action.dest == "func":
                continue
            flags = ", ".join(f"`{o}`" for o in action.option_strings) \
                or f"`<{action.dest}>`"
            default = ""
            if action.default not in (None, False) and action.option_strings:
                default = f"`{action.default}`"
            choices = ", ".join(f"`{c}`" for c in action.choices) \
                if action.choices else ""
            rows.append([flags, (action.help or "").strip(), choices, default])
        if rows:
            table(out, ["Option", "Meaning", "Choices", "Default"], rows)

    # -- the CMTS shell -------------------------------------------------
    lab = Lab(Topology(), LabOptions(speed=0.0, capture_path=None, echo=False))
    cli = Cli(lab)
    w("## The CMTS shell\n\n")
    w("Inside `docsis cli`. Unambiguous abbreviations work, so `sh ca mo` is "
      "`show cable modem`. A single command can also be run without attaching "
      "an interactive shell:\n\n")
    w("```sh\n./docsis cli show cable modem\n```\n\n")

    groups: dict[str, list] = {}
    for cmd in cli.commands:
        if cmd.words == ("?",):
            continue
        key = {"show": "Inspecting", "clear": "Acting",
               "test": "Acting", "ping": "Acting",
               "debug": "Acting"}.get(cmd.words[0], "Other")
        groups.setdefault(key, []).append(cmd)
    for key in ("Inspecting", "Acting", "Other"):
        if key not in groups:
            continue
        w(f"### {key}\n\n")
        table(out, ["Command", "Purpose"],
              [[f"`{' '.join(c.words)}" + (f" {c.args}" if c.args else "") + "`",
                c.help] for c in groups[key]])
    lab.close()
    return out.getvalue()


# --------------------------------------------------------------------------
# API.md
# --------------------------------------------------------------------------

PACKAGE_BLURB = {
    "docsislab.util": "Byte-level plumbing with no DOCSIS knowledge in it.",
    "docsislab.docsis": "The protocol itself: framing, messages, the "
                        "configuration file, and the constants.",
    "docsislab.phy": "Channel parameters, the byte/mini-slot arithmetic, and "
                     "the HFC plant that carries every frame.",
    "docsislab.cmts": "The CMTS.",
    "docsislab.cm": "The cable modem, and a host to sit behind it.",
    "docsislab.net": "Networking: packet encoding, the provisioning "
                     "protocols, a small IP stack, and the macOS utun bridge.",
    "docsislab.provisioning": "The DHCP, Time-of-Day and TFTP host on the "
                              "CMTS's network side.",
    "docsislab.lab": "Wiring, scheduling and the operator front ends.",
}


def first_sentence(doc: str | None) -> str:
    if not doc:
        return ""
    text = inspect.cleandoc(doc).split("\n\n")[0].replace("\n", " ").strip()
    return text


def api_doc() -> str:
    out = io.StringIO()
    w = out.write
    w("# Module map\n\n")
    w(GENERATED + "\n\n")
    w("What lives where, from the package's own docstrings. The one structural "
      "rule worth stating: the CMTS and the cable modems hold no reference to "
      "each other. Everything between them goes through `phy.plant`, which is "
      "what keeps the simulation honest -- if a modem gets online, it did so "
      "by exchanging real DOCSIS frames.\n\n")

    modules = sorted(p for p in ROOT.glob("docsislab/**/*.py")
                     if p.name != "__init__.py")
    by_package: dict[str, list[pathlib.Path]] = {}
    for path in modules:
        package = ".".join(path.relative_to(ROOT).parts[:-1])
        by_package.setdefault(package, []).append(path)

    for package in sorted(by_package):
        w(f"## `{package}`\n\n")
        blurb = PACKAGE_BLURB.get(package)
        if blurb:
            w(blurb + "\n\n")
        for path in sorted(by_package[package]):
            tree = ast.parse(path.read_text(), str(path))
            module_doc = first_sentence(ast.get_docstring(tree))
            rel = path.relative_to(ROOT)
            lines = len(path.read_text().splitlines())
            w(f"### `{rel}`\n\n")
            if module_doc:
                w(f"{module_doc}\n\n")
            rows = []
            plain: list[str] = []
            for node in tree.body:
                if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
                    kind = "class"
                elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) \
                        and not node.name.startswith("_"):
                    kind = "function"
                else:
                    continue
                purpose = first_sentence(ast.get_docstring(node))
                if purpose:
                    rows.append([f"`{node.name}`", kind, purpose])
                else:
                    plain.append(node.name)
            if rows:
                table(out, ["Name", "Kind", "Purpose"], rows)
            if plain:
                # Self-describing helpers, listed rather than tabulated with
                # an empty column.
                w("Also: " + ", ".join(f"`{n}`" for n in plain) + ".\n\n")
            if not rows and not plain:
                w(f"{lines} lines.\n\n")
    return out.getvalue()


# --------------------------------------------------------------------------
# index
# --------------------------------------------------------------------------

def index_doc() -> str:
    out = io.StringIO()
    w = out.write
    w("# Documentation\n\n")
    w(GENERATED + "\n\n")
    table(out, ["Document", "Written or generated", "Contents"], [
        ["[../README.md](../README.md)", "written",
         "what this is, how to run it, what is real and what is modelled"],
        ["[DOCSIS-NOTES.md](DOCSIS-NOTES.md)", "written",
         "how a modem comes online, step by step, with the log lines and "
         "filters that show each one"],
        ["[WIRESHARK.md](WIRESHARK.md)", "written",
         "how the wire format was verified against Wireshark's dissector, "
         "including the two bugs it found"],
        ["[REFERENCE.md](REFERENCE.md)", "generated",
         "message types, IUCs, every TLV namespace, timers, and the channel "
         "and plant arithmetic"],
        ["[CLI.md](CLI.md)", "generated",
         "every `docsis` subcommand and every CMTS shell command"],
        ["[API.md](API.md)", "generated", "module map"],
    ])
    w("The generated documents come out of `tools/gen_docs.py`, which reads "
      "the code rather than a copy of it:\n\n")
    w("```sh\n./docsis docs           # regenerate\n"
      "./docsis docs --check   # fail if stale (also a test)\n```\n\n")
    w("## Where to start\n\n")
    w("Run it once, then read the capture:\n\n")
    w("```sh\n./docsis run\nopen captures/docsis.pcapng\n"
      "./docsis pcap                 # or a text summary\n```\n\n")
    w("`DOCSIS-NOTES.md` follows the same sequence in prose. `REFERENCE.md` is "
      "for when you are staring at a byte and want to know what it means.\n")
    return out.getvalue()


DOCUMENTS = {
    "REFERENCE.md": reference,
    "CLI.md": cli_doc,
    "API.md": api_doc,
    "README.md": index_doc,
}


def generate() -> dict[str, str]:
    return {name: fn() for name, fn in DOCUMENTS.items()}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Generate the reference docs.")
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the docs on disk are stale")
    ap.add_argument("--out", default=str(DOCS))
    args = ap.parse_args(argv)

    target = pathlib.Path(args.out)
    target.mkdir(parents=True, exist_ok=True)
    stale = []
    for name, text in generate().items():
        path = target / name
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(name)
            continue
        path.write_text(text)
        print(f"wrote {path.relative_to(ROOT) if target == DOCS else path} "
              f"({len(text.splitlines())} lines)")
    if args.check:
        if stale:
            print("stale documentation: " + ", ".join(stale), file=sys.stderr)
            print("run ./docsis docs to regenerate", file=sys.stderr)
            return 1
        print("documentation is up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
